[project]
project_id = "ahbjwpkpxqqrpvpzmqwa"

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send]
verify_jwt = true

[functions.automation-webhook]
verify_jwt = false

[functions.automation-send]
verify_jwt = false

[functions.catalog-api]
verify_jwt = false
